/**
 * Created by atide on 2016/10/28.
 */
//首页ACTIONTYPE
export const FETCH_HOME_LIST = 'FETCH_HOME_IMAGE_LIST';
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_IMAGE_LIST';

//动态页ACTIONTYPE
export const FETCH_DYNAMIC_LIST = 'FETCH_DYNAMIC_LIST';
export const RECEIVE_DYNAMIC_LIST = 'RECEIVE_DYNAMIC_LIST';

//收藏页ACTIONTYPE
export const FETCH_COLLECTION_LIST = 'FETCH_COLLECTION_LIST';
export const RECEIVE_COLLECTION_LIST = 'RECEIVE_COLLECTION_LIST';
